"""Pydantic v2 schemas for request/response payloads."""

from .assignment import (
    AssignmentCreate,
    AssignmentDeadlines,
    AssignmentDeadlinesUpdate,
    AssignmentDuplicate,
    AssignmentRead,
    AssignmentUpdate,
    DeadlineExtensionCreate,
    DeadlineExtensionRead,
    EffectiveDeadline,
    ExternalBinding,
    GradingConfigRead,
    GradingConfigUpdate,
    StatsTimelinePoint,
)
from .course import (
    CourseCreate,
    CourseDuplicate,
    CourseRead,
    CourseStats,
    CourseUpdate,
    DashboardSummary,
)
from .group import GroupCreate, GroupMemberRead, GroupRead, GroupUpdate
from .homework import (
    HomeworkCreate,
    HomeworkRead,
    HomeworkReorder,
    HomeworkStatus,
    HomeworkUpdate,
)
from .invitation import InvitationCreate, InvitationRead, JoinByCodeRequest, JoinByCodeResponse
from .member import (
    BatchMemberCreate,
    BulkInviteRequest,
    BulkInviteResponse,
    MemberCreate,
    MemberRead,
    MemberRoleUpdate,
    MemberTransferGroup,
    OwnerCreate,
    OwnerRead,
)

__all__ = [
    "AssignmentCreate",
    "AssignmentDeadlines",
    "AssignmentDeadlinesUpdate",
    "AssignmentDuplicate",
    "AssignmentRead",
    "AssignmentUpdate",
    "BatchMemberCreate",
    "BulkInviteRequest",
    "BulkInviteResponse",
    "CourseCreate",
    "CourseDuplicate",
    "CourseRead",
    "CourseStats",
    "CourseUpdate",
    "DashboardSummary",
    "DeadlineExtensionCreate",
    "DeadlineExtensionRead",
    "EffectiveDeadline",
    "ExternalBinding",
    "GradingConfigRead",
    "GradingConfigUpdate",
    "GroupCreate",
    "GroupMemberRead",
    "GroupRead",
    "GroupUpdate",
    "HomeworkCreate",
    "HomeworkRead",
    "HomeworkReorder",
    "HomeworkStatus",
    "HomeworkUpdate",
    "InvitationCreate",
    "InvitationRead",
    "JoinByCodeRequest",
    "JoinByCodeResponse",
    "MemberCreate",
    "MemberRead",
    "MemberRoleUpdate",
    "MemberTransferGroup",
    "OwnerCreate",
    "OwnerRead",
    "StatsTimelinePoint",
]
